import { NextRequest, NextResponse } from 'next/server';
import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { requireAdmin } from '@lib/auth/admin-middleware';
import { getRequiredEnv, getOptionalEnv } from '@lib/env';
import { logger } from '@lib/logger';
import { applyRateLimit } from '@/lib/rate-limit';

function getEncryptionKey(): string {
  const key = process.env.CREDENTIALS_ENCRYPTION_KEY;
  if (!key && process.env.NODE_ENV === 'production') {
    throw new Error('CREDENTIALS_ENCRYPTION_KEY é obrigatório em produção');
  }
  return key || 'dev-only-encryption-key-not-for-production';
}
const ENV_FILE = '.env.production';

function encrypt(text: string): string {
  const ENCRYPTION_KEY = getEncryptionKey();
  const algorithm = 'aes-256-cbc';
  const key = crypto.scryptSync(ENCRYPTION_KEY, ENCRYPTION_KEY.substring(0, 16), 32);
  const iv = crypto.randomBytes(16);
  const cipher = crypto.createCipheriv(algorithm, key, iv);
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return iv.toString('hex') + ':' + encrypted;
}

interface EnvVariable {
  key: string;
  value: string;
  isSecret: boolean;
}

// GET - Obter variáveis de ambiente
export async function GET(request: NextRequest) {
    const rateLimitBlocked = await applyRateLimit(request, 'admin-environment-get', 30);
    if (rateLimitBlocked) return rateLimitBlocked;

  const { isAdmin, response } = await requireAdmin(request);
  if (!isAdmin) return response!;

  try {
    const envPath = path.join(process.cwd(), ENV_FILE);
    const variables: EnvVariable[] = [];

    try {
      const content = await fs.readFile(envPath, 'utf8');
      const lines = content.split('\n');

      lines.forEach(line => {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#')) {
          const [key, ...valueParts] = trimmed.split('=');
          const value = valueParts.join('=');
          if (key) {
            variables.push({
              key: key.trim(),
              value: value.trim(),
              isSecret: key.includes('KEY') || key.includes('SECRET') || key.includes('PASSWORD') || key.includes('TOKEN')
            });
          }
        }
      });
    } catch {
      // Arquivo não existe, retornar variáveis de ambiente atuais
      const defaultVars = [
        'NODE_ENV',
        'NEXT_PUBLIC_SUPABASE_URL',
        'NEXT_PUBLIC_SUPABASE_ANON_KEY',
        'SUPABASE_SERVICE_ROLE_KEY',
        'DIRECT_DATABASE_URL',
        'REDIS_URL',
        'ELEVENLABS_API_KEY',
        'HEYGEN_API_KEY',
        'OPENAI_API_KEY',
        'AZURE_SPEECH_KEY',
        'AZURE_SPEECH_REGION',
        'AWS_ACCESS_KEY_ID',
        'AWS_SECRET_ACCESS_KEY',
        'AWS_REGION',
        'AWS_S3_BUCKET',
        'NEXTAUTH_SECRET',
        'NEXTAUTH_URL',
        'SENTRY_DSN',
        'LOG_LEVEL',
        'ADMIN_EMAIL'
      ];

      defaultVars.forEach(key => {
        const value = process.env[key];
        if (value) {
          variables.push({
            key,
            value,
            isSecret: key.includes('KEY') || key.includes('SECRET') || key.includes('PASSWORD') || key.includes('TOKEN')
          });
        }
      });
    }

    return NextResponse.json({ variables });

  } catch (error) {
    logger.error('Erro ao obter variáveis de ambiente', error instanceof Error ? error : new Error(String(error)), {
      component: 'API: admin/environment'
    });
    return NextResponse.json(
      { error: 'Erro ao obter variáveis de ambiente' },
      { status: 500 }
    );
  }
}

// POST - Salvar variáveis de ambiente
export async function POST(request: NextRequest) {
  const { isAdmin, response } = await requireAdmin(request);
  if (!isAdmin) return response!;

  try {
    const { variables } = await request.json() as { variables: EnvVariable[] };

    if (!variables || !Array.isArray(variables)) {
      return NextResponse.json(
        { error: 'Variáveis inválidas' },
        { status: 400 }
      );
    }

    // Gerar conteúdo do arquivo .env
    const header = `# ============================================
# Production Environment Variables
# Generated by Admin Panel
# ${new Date().toISOString()}
# ============================================

`;

    const content = variables
      .filter(v => v.key && v.value)
      .map(v => `${v.key}=${v.value}`)
      .join('\n');

    const envPath = path.join(process.cwd(), ENV_FILE);
    await fs.writeFile(envPath, header + content + '\n', 'utf8');

    logger.info('Variáveis de ambiente salvas', {
      component: 'API: admin/environment',
      count: variables.length,
      timestamp: new Date().toISOString()
    });

    return NextResponse.json({
      success: true,
      message: 'Variáveis de ambiente salvas com sucesso',
      count: variables.length
    });

  } catch (error) {
    logger.error('Erro ao salvar variáveis de ambiente', error instanceof Error ? error : new Error(String(error)), {
      component: 'API: admin/environment'
    });
    return NextResponse.json(
      { error: 'Erro ao salvar variáveis de ambiente' },
      { status: 500 }
    );
  }
}
