#!/bin/bash
# ============================================
# MVP Video TécnicoCursos v7 - Deploy App
# Execute com: curl -fsSL https://raw.githubusercontent.com/jessegabrielstain-debug/_MVP_Video_TecnicoCursos_v7/main/scripts/deploy/deploy-app.sh | bash
# ============================================

set -e

echo ""
echo "🚀 ============================================"
echo "🚀 Iniciando Deploy da Aplicação"
echo "🚀 ============================================"
echo ""

# Variáveis
REPO_URL="https://github.com/jessegabrielstain-debug/_MVP_Video_TecnicoCursos_v7.git"
APP_DIR="/opt/mvp"
PROJECT_DIR="$APP_DIR/_MVP_Video_TecnicoCursos_v7"

# 1. Criar diretório
echo "📁 Criando diretório da aplicação..."
mkdir -p $APP_DIR
cd $APP_DIR

# 2. Clonar ou atualizar repositório
if [ -d "$PROJECT_DIR" ]; then
    echo "📦 Atualizando repositório existente..."
    cd $PROJECT_DIR
    git fetch origin
    git reset --hard origin/main
else
    echo "📦 Clonando repositório..."
    git clone $REPO_URL
    cd $PROJECT_DIR
fi

# 3. Criar diretórios necessários
echo "📁 Criando diretórios necessários..."
mkdir -p redis nginx/ssl logs/nginx nginx/snippets

# 4. Criar redis.conf
echo "⚙️ Configurando Redis..."
cat > redis/redis.conf <<'REDIS_EOF'
bind 0.0.0.0
protected-mode no
port 6379
save 60 1000
appendonly yes
appendfsync everysec
maxmemory 512mb
maxmemory-policy allkeys-lru
loglevel notice
REDIS_EOF

# 5. Criar snippets do Nginx
echo "⚙️ Configurando Nginx snippets..."
cat > nginx/snippets/security-headers.conf <<'NGINX_SECURITY'
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-XSS-Protection "1; mode=block" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
NGINX_SECURITY

cat > nginx/snippets/proxy-params.conf <<'NGINX_PROXY'
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection 'upgrade';
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_cache_bypass $http_upgrade;
NGINX_PROXY

# 6. Criar docker-compose.override.yml
echo "⚙️ Configurando Docker Compose override..."
cat > docker-compose.override.yml <<'OVERRIDE_EOF'
services:
  nginx:
    volumes:
      - ./nginx/snippets:/etc/nginx/snippets:ro
OVERRIDE_EOF

# 7. Ajustar Nginx para aceitar qualquer host
echo "⚙️ Ajustando Nginx server_name..."
if [ -f nginx/conf.d/app.conf ]; then
    sed -i 's/server_name cursostecno.com.br www.cursostecno.com.br;/server_name _;/' nginx/conf.d/app.conf
    echo "✅ Nginx configurado para aceitar qualquer host"
else
    echo "⚠️ nginx/conf.d/app.conf não encontrado"
fi

# 8. Criar .env.production se não existir
if [ ! -f .env.production ]; then
    echo "⚙️ Criando .env.production..."
    cat > .env.production <<'ENV_EOF'
# ============================================
# Production Environment Variables
# Generated by deploy-app.sh
# ============================================

NODE_ENV=production

# Redis
REDIS_URL=redis://redis:6379

# Logging
LOG_LEVEL=info

# Admin Panel
ADMIN_EMAIL=admin@cursostecno.com.br
ADMIN_PASSWORD=Admin@123

# Supabase (preencher depois no painel admin)
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=
DIRECT_DATABASE_URL=

# APIs (preencher depois no painel admin)
ELEVENLABS_API_KEY=
HEYGEN_API_KEY=
OPENAI_API_KEY=
ENV_EOF
    echo "✅ .env.production criado"
else
    echo "✅ .env.production já existe"
fi

# 9. Verificar Docker
echo ""
echo "🐳 Verificando Docker..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker não instalado!"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo "❌ Docker não está rodando!"
    exit 1
fi

echo "✅ Docker OK"

# 10. Parar containers existentes
echo ""
echo "🛑 Parando containers existentes..."
docker compose -f docker-compose.prod.yml down 2>/dev/null || true

# 11. Build e Start
echo ""
echo "🔨 Construindo e iniciando containers..."
echo "⏱️ Isso pode levar 5-15 minutos na primeira vez..."
echo ""

docker compose -f docker-compose.prod.yml up -d --build

# 12. Aguardar containers iniciarem
echo ""
echo "⏳ Aguardando containers iniciarem..."
sleep 10

# 13. Verificar status
echo ""
echo "📊 Status dos containers:"
docker compose -f docker-compose.prod.yml ps

# 14. Verificar health
echo ""
echo "🏥 Verificando saúde da aplicação..."
for i in {1..30}; do
    if curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/health | grep -q "200"; then
        echo "✅ Aplicação respondendo!"
        break
    fi
    echo "⏳ Tentativa $i/30..."
    sleep 5
done

# 15. Resultado final
echo ""
echo "🎉 ============================================"
echo "🎉 DEPLOY CONCLUÍDO!"
echo "🎉 ============================================"
echo ""
echo "📍 Acesse:"
echo "   • Aplicação:    http://$(curl -s ifconfig.me 2>/dev/null || echo '168.231.90.64')"
echo "   • Admin Panel:  http://$(curl -s ifconfig.me 2>/dev/null || echo '168.231.90.64')/admin/login"
echo ""
echo "🔐 Credenciais Admin:"
echo "   • Email: admin@cursostecno.com.br"
echo "   • Senha: Admin@123"
echo ""
echo "📝 Próximo passo:"
echo "   Acesse o painel admin e configure as credenciais:"
echo "   - Supabase URL e Keys"
echo "   - ElevenLabs API Key"
echo "   - HeyGen API Key"
echo ""
echo "🔧 Comandos úteis:"
echo "   • Ver logs:     docker compose -f docker-compose.prod.yml logs -f"
echo "   • Reiniciar:    docker compose -f docker-compose.prod.yml restart"
echo "   • Parar:        docker compose -f docker-compose.prod.yml down"
echo ""
